networks:
  dr_net:
    driver: bridge

services:

  primary_app:
    build: ./app
    container_name: primary_app
    restart: unless-stopped
    networks:
      - dr_net
    environment:
      - DB_PATH=/data/primary/application.db
    volumes:
      - ./data/primary:/data/primary
    ports:
      - "5001:5000"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  dr_app:
    build: ./app
    container_name: dr_app
    restart: unless-stopped
    networks:
      - dr_net
    environment:
      - DB_PATH=/data/dr/application.db
    volumes:
      - ./data/dr:/data/dr
    ports:
      - "5002:5000"
    deploy:
      replicas: 0
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  primary_localstack:
    image: localstack/localstack
    container_name: primary_localstack
    restart: unless-stopped
    networks:
      - dr_net
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ec2
      - DEFAULT_REGION=${PRIMARY_REGION}
      - DEBUG=1
    volumes:
      - "./localstack_primary_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-primary.sh:/etc/localstack/init/ready.d/init-primary.sh"

  dr_localstack:
    image: localstack/localstack
    container_name: dr_localstack
    restart: unless-stopped
    networks:
      - dr_net
    ports:
      - "4567:4566"
    environment:
      - SERVICES=s3,ec2
      - DEFAULT_REGION=${DR_REGION}
      - DEBUG=1
    volumes:
      - "./localstack_dr_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./scripts/init-dr.sh:/etc/localstack/init/ready.d/init-dr.sh"